services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    tty: true
    stdin_open: true
    command: go run main.go  # Changed from ./main to go run main.go
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  postgres_data: