services:
  web:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - HTTP_PROXY=http://10.84.142.62:3128/
      - HTTPS_PROXY=http://10.84.142.62:3128/
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
