version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${MyTcell_DB_USER}
      POSTGRES_PASSWORD: ${MyTcell_DB_PASSWORD}
      POSTGRES_DB: ${MyTcell_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data: