services:
  web:
    build: .
    volumes:
      # - .:/app
      - go-modules:/go/pkg/mod
    working_dir: /app
    ports:
      - "3001:3001"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
    command: ./main  # This will run the built executable

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  go-modules:
  postgres_data: